name: lint
  
on:
  push:
    branches: ["*"]

jobs:
  lint-server:
    runs-on: self-hosted 
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Check file formatting
        run: |
          UNFORMATTED=$(gofmt -l .)
          if [ -n "$UNFORMATTED" ]; then
            echo "Unformatted files:"
            echo "$UNFORMATTED"
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

  lint-client:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci
      - name: Check file formatting
        run: npx prettier . --check
